# Generated by Django 4.1.4 on 2022-12-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'Movies'},
        ),
    ]
