# Generated by Django 4.1.4 on 2023-03-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
