# Generated by Django 4.1.5 on 2023-04-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0008_review_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name_plural': 'Watch Lists'},
        ),
    ]
